import { app, BrowserWindow, screen } from "electron";
import isDev from "electron-is-dev";
import * as fs from "fs";
import * as path from "path";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

type DisplayBounds = { x: number; y: number; width: number; height: number };
type MainWindowState = {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  isMaximized?: boolean;
  displayBounds?: DisplayBounds;
};

type LoadedMainWindowState = {
  x?: number;
  y?: number;
  width: number;
  height: number;
  isMaximized: boolean;
  displayBounds?: DisplayBounds;
};

const MAIN_WINDOW_STATE_FILE = "main-window-state.json";
const DEFAULT_WINDOW_WIDTH = 800;
const DEFAULT_WINDOW_HEIGHT = 600;

const getMainWindowStatePath = (): string =>
  path.join(app.getPath("userData"), MAIN_WINDOW_STATE_FILE);

const hasValidBounds = (
  state: LoadedMainWindowState,
): state is LoadedMainWindowState &
  Required<Pick<LoadedMainWindowState, "x" | "y" | "width" | "height">> =>
  Number.isInteger(state.x) &&
  Number.isInteger(state.y) &&
  Number.isInteger(state.width) &&
  Number.isInteger(state.height) &&
  (state.width ?? 0) > 0 &&
  (state.height ?? 0) > 0;

const isWithin = (
  state: Required<Pick<LoadedMainWindowState, "x" | "y" | "width" | "height">>,
  bounds: DisplayBounds,
): boolean =>
  state.x >= bounds.x &&
  state.y >= bounds.y &&
  state.x + state.width <= bounds.x + bounds.width &&
  state.y + state.height <= bounds.y + bounds.height;

const loadMainWindowState = (): LoadedMainWindowState => {
  const fallback: LoadedMainWindowState = {
    width: DEFAULT_WINDOW_WIDTH,
    height: DEFAULT_WINDOW_HEIGHT,
    isMaximized: false,
  };

  try {
    const raw = fs.readFileSync(getMainWindowStatePath(), "utf8");
    const parsed = JSON.parse(raw) as MainWindowState;

    const merged: LoadedMainWindowState = {
      ...fallback,
      x: Number.isFinite(parsed.x) ? parsed.x : undefined,
      y: Number.isFinite(parsed.y) ? parsed.y : undefined,
      width: Number.isFinite(parsed.width) ? parsed.width : fallback.width,
      height: Number.isFinite(parsed.height) ? parsed.height : fallback.height,
      isMaximized: Boolean(parsed.isMaximized),
      displayBounds:
        parsed.displayBounds &&
        Number.isFinite(parsed.displayBounds.x) &&
        Number.isFinite(parsed.displayBounds.y) &&
        Number.isFinite(parsed.displayBounds.width) &&
        Number.isFinite(parsed.displayBounds.height)
          ? parsed.displayBounds
          : undefined,
    };

    if (!hasValidBounds(merged)) {
      return merged;
    }

    const displays = screen.getAllDisplays();
    const visible = displays.some((d) =>
      isWithin(merged, d.bounds as unknown as DisplayBounds),
    );
    if (!visible) {
      return {
        ...merged,
        x: undefined,
        y: undefined,
      };
    }

    return merged;
  } catch {
    return fallback;
  }
};

const saveMainWindowState = (win: BrowserWindow): void => {
  try {
    const normalBounds = win.getNormalBounds();
    const displayBounds = (screen.getDisplayMatching(win.getBounds()).bounds ??
      undefined) as DisplayBounds | undefined;

    const state: MainWindowState = {
      x: normalBounds.x,
      y: normalBounds.y,
      width: normalBounds.width,
      height: normalBounds.height,
      isMaximized: win.isMaximized(),
      displayBounds,
    };

    fs.mkdirSync(path.dirname(getMainWindowStatePath()), { recursive: true });
    fs.writeFileSync(getMainWindowStatePath(), JSON.stringify(state));
  } catch {
    // Ignore persistence errors
  }
};

const createWindow = (): void => {
  const mainWindowState = loadMainWindowState();

  // Create the browser window.
  const browserWindowOptions: Electron.BrowserWindowConstructorOptions = {
    width: mainWindowState.width,
    height: mainWindowState.height,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  };

  if (mainWindowState.isMaximized && mainWindowState.displayBounds) {
    browserWindowOptions.x = mainWindowState.displayBounds.x + 50;
    browserWindowOptions.y = mainWindowState.displayBounds.y + 50;
  } else {
    if (typeof mainWindowState.x === "number") {
      browserWindowOptions.x = mainWindowState.x;
    }
    if (typeof mainWindowState.y === "number") {
      browserWindowOptions.y = mainWindowState.y;
    }
  }

  const mainWindow = new BrowserWindow(browserWindowOptions);

  let saveWindowStateTimer: NodeJS.Timeout | undefined;
  const scheduleSaveWindowState = (): void => {
    if (saveWindowStateTimer) {
      clearTimeout(saveWindowStateTimer);
    }
    saveWindowStateTimer = setTimeout(() => {
      saveMainWindowState(mainWindow);
    }, 250);
  };

  const saveWindowStateNow = (): void => {
    if (saveWindowStateTimer) {
      clearTimeout(saveWindowStateTimer);
      saveWindowStateTimer = undefined;
    }
    saveMainWindowState(mainWindow);
  };

  mainWindow.on("move", scheduleSaveWindowState);
  mainWindow.on("resize", scheduleSaveWindowState);
  mainWindow.on("maximize", scheduleSaveWindowState);
  mainWindow.on("unmaximize", scheduleSaveWindowState);
  mainWindow.on("close", saveWindowStateNow);

  if (mainWindowState.isMaximized) {
    mainWindow.maximize();
  }

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (isDev) {
    mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
